### ISSUE TITLE
Incorrect error code for user not found

### ISSUE THREAD

**Issue by hnngo** [fc5y/user-backend#41]
## Description
- Currently, api `/api/v1/user/:id` will return error 4002 `System Error`.

## Environment
- Current version

## Steps to reproduce
- Always reproduce
- Call api `/api/v1/user/abcfake`

## Expected behaviour
- Be able to get the response with `code = 2001` (User not found)

## Actual behaviour
- Get error code `code = 4200` (System Error).

![image](https://user-images.githubusercontent.com/43344276/101284069-291c7200-3819-11eb-9725-d8ecc997a41e.png)

**Comment by dothanhlam97** [comment]
cc: @ndkhaivn Kh

**Comment by hnngo** [comment]
is this problem fixed? @dothanhlam97 @kc97ble @houtaru @pythagore1123
